### ISSUE TITLE
Generating good images with discogan

### ISSUE THREAD

**Issue by chinmayjog13** [haibo-qiu/SynFace#8]
Did you have any trouble generating face images with discogan?
I tried both their original code, and your test code, but I all I get is noise
![000_00](https://github.com/haibo-qiu/SynFace/assets/37167529/eebac08d-0790-46fb-946e-8f5c03576dac)

The discoGan repo does not seem maintained at this time, so wondering if you can help me

**Comment by haibo-qiu** [comment]
Hi @chinmayjog13,

I have never encountered the situation like the one you provided when using discofacegan.

You may need to verify if all types of pretrained models have been downloaded correctly. Additionally, this issue could be caused by different versions of certain packages.

By the way, I thoroughly checked all my code based on this [commit](https://github.com/microsoft/DiscoFaceGAN/tree/146e553d1929847b8add26c40a92014f4b05a27b) of discofacegan before publicly releasing the repo and obtained expected results. You may try it.

**Comment by chinmayjog13** [comment]
Thanks, I will try it. When you say certain package versions can cause errors, do you know which packages and which versions?

**Comment by haibo-qiu** [comment]
No, I don't know. As I mentioned earlier, I have never encountered a similar situation. 
What I said is just a potential explanation for the issue.

**Comment by haibo-qiu** [comment]
If you have any more questions, please feel free to reopen this issue.
